export const insuranceListIndex = {
  'health': {
    "myself": [1, 2, 3, 4, 5, 6],
    "family": [1, 2, 3, 4, 5, 6],
    "children": [1, 2, 3, 4, 5, 6],
    "other": [1, 2, 3, 4, 5, 6],
  },
  'dental': {
    "myself": [7],
    "family": [8],
    "children": [7, 8],
    "other": [7, 8],
  },
  'life': {
    "myself": [9, 10],
    "family": [9, 10],
    "children": [9, 10],
    "other": [9, 10],
  },
  'accidents': {
    "myself": [11, 12, 13],
    "family": [11, 12, 13],
    "children": [11, 12, 13],
    "other": [11, 12, 13],
  },
  'hospitalization': {
    "myself": [14],
    "family": [14],
    "children": [14],
    "other": [14],
  },
  'passing': {
    "myself": [15],
    "family": [15],
    "children": [15],
    "other": [15],
  },
  'pets': {
    "myself": [16],
    "family": [16],
    "children": [16],
    "other": [16],
  },

  'travel': {
    "myself": [17, 18, 19, 20],
    "family": [17, 18, 19, 20],
    "children": [20],
    "other": [17, 18, 19, 20],
  },
}
export const loadInsuranceList = (t) => ([
  {
    id: 1,
    title: t('Asisa Completa ++'),
    description: t('Cobertura completa al mejor precio y con un copago un poco más alto. El producto estrella de ASISA.'),
    price: [18, 5],
    variant: t('Copago alto'),
    coverages: [
      { name: t('Consultas en medicina primaria y especializada'), icon: 'covered' },
      { name: t('Pruebas diagnósticas'), icon: 'covered' },
      { name: t('Tratamientos especiales'), icon: 'covered' },
      { name: t('Hospitalización'), icon: 'covered' },
      { name: t('Cirugía ambulatoria'), icon: 'covered' },
      { name: t('Traslado en ambulancia'), icon: 'covered' },
      { name: t('Prótesis e implantes'), icon: 'covered' },
      { name: t('Trasplantes'), icon: 'covered' },
      { name: t('Indemnización fallecimiento por accidente'), icon: 'not-covered' },
    ]
  },
  {
    id: 2,
    title: t('Asisa Ya'),
    description: t('Cobertura ambulatoria al mejor precio y con un copago un poco más alto. El producto ambulatorio estrella de ASISA.'),
    price: [10, 50],
    variant: t('Copago alto'),
    coverages: [
      { name: t('Consultas en medicina primaria y especializada'), icon: 'covered', },
      { name: t('Pruebas diagnósticas'), icon: 'covered', },
      { name: t('Tratamientos especiales'), icon: 'maybe', },
      { name: t('Hospitalización'), icon: 'not-covered', },
      { name: t('Cirugía ambulatoria'), icon: 'not-covered', },
      { name: t('Traslado en ambulancia'), icon: 'covered', },
      { name: t('Prótesis e implantes'), icon: 'not-covered', },
      { name: t('Trasplantes'), icon: 'not-covered', },
      { name: t('Indemnización fallecimiento por accidente'), icon: 'not-covered', },
    ]
  },
  {
    id: 3,
    title: t('Asisa Completa +'),
    description: t('Cobertura completa con un precio muy competitivo y un copago bajo. El seguro más vendido de ASISA.'),
    price: [26, 80],
    variant: t('Copago bajo'),
    coverages: [
      { name: t('Consultas en medicina primaria y especializada'), icon: 'covered', },
      { name: t('Pruebas diagnósticas'), icon: 'covered', },
      { name: t('Tratamientos especiales'), icon: 'covered', },
      { name: t('Hospitalización'), icon: 'covered', },
      { name: t('Cirugía ambulatoria'), icon: 'covered', },
      { name: t('Traslado en ambulancia'), icon: 'covered', },
      { name: t('Prótesis e implantes'), icon: 'covered', },
      { name: t('Trasplantes'), icon: 'covered', },
      { name: t('Indemnización fallecimiento por accidente'), icon: 'not-covered', },
    ]
  },
  {
    id: 4,
    title: t('Asisa Completa'),
    description: t('Cobertura completa con un precio muy competitivo y sin copago. El seguro más vendido de ASISA.'),
    price: [48, 70],
    variant: t('Sin copago'),
    coverages: [
      { name: t('Consultas en medicina primaria y especializada'), icon: 'covered', },
      { name: t('Pruebas diagnósticas'), icon: 'covered', },
      { name: t('Tratamientos especiales'), icon: 'covered', },
      { name: t('Hospitalización'), icon: 'covered', },
      { name: t('Cirugía ambulatoria'), icon: 'covered', },
      { name: t('Traslado en ambulancia'), icon: 'covered', },
      { name: t('Prótesis e implantes'), icon: 'covered', },
      { name: t('Trasplantes'), icon: 'covered', },
      { name: t('Indemnización fallecimiento por accidente'), icon: 'not-covered', },
    ]
  },
  {
    id: 5,
    title: t('Asisa Esencial +'),
    description: t('Cobertura ambulatoria (no cubre hospitalización) con un precio muy económico y un copago bajo.'),
    price: [21, 0],
    variant: t('Copago bajo'),
    coverages: [
      { name: t('Consultas en medicina primaria y especializada'), icon: 'covered', },
      { name: t('Pruebas diagnósticas'), icon: 'covered', },
      { name: t('Tratamientos especiales'), icon: 'maybe', },
      { name: t('Hospitalización'), icon: 'not-covered', },
      { name: t('Cirugía ambulatoria'), icon: 'not-covered', },
      { name: t('Traslado en ambulancia'), icon: 'covered', },
      { name: t('Prótesis e implantes'), icon: 'not-covered', },
      { name: t('Trasplantes'), icon: 'not-covered', },
      { name: t('Indemnización fallecimiento por accidente'), icon: 'not-covered', },
    ]
  },
  {
    id: 6,
    title: t('Asisa Esencial'),
    description: t('Cobertura ambulatoria (no cubre hospitalización) con un precio muy económico y sin copago.'),
    price: [31, 0],
    variant: t('Sin copago'),
    coverages: [
      { name: t('Consultas en medicina primaria y especializada'), icon: 'covered', },
      { name: t('Pruebas diagnósticas'), icon: 'covered', },
      { name: t('Tratamientos especiales'), icon: 'maybe', },
      { name: t('Hospitalización'), icon: 'not-covered', },
      { name: t('Cirugía ambulatoria'), icon: 'not-covered', },
      { name: t('Traslado en ambulancia'), icon: 'covered', },
      { name: t('Prótesis e implantes'), icon: 'not-covered', },
      { name: t('Trasplantes'), icon: 'not-covered', },
      { name: t('Indemnización fallecimiento por accidente'), icon: 'not-covered', },
    ]
  },
  {
    id: 7,
    title: t('Asisa Dental'),
    description: t('Seguro dental individual con un gran número de coberturas, tratamientos y una gran red de clínicas a nivel nacional.'),
    price: [8, 40],
    variant: undefined,
    coverages: [
      { name: t('Múltiples servicios cubiertos por la póliza sin franquicia'), icon: 'covered' },
      { name: t('Pruebas diagnósticas'), icon: 'covered' },
      { name: t('Odontología preventiva y conservadora'), icon: 'covered' },
      { name: t('Endodoncia'), icon: 'covered' },
      { name: t('Odontopediatría'), icon: 'covered' },
      { name: t('Periodoncia'), icon: 'covered' },
      { name: t('Ortodoncia'), icon: 'covered' },
      { name: t('Prótesis e implantes'), icon: 'covered' },
      { name: t('Cirugía'), icon: 'covered' },
      { name: t('Estética dental'), icon: 'covered' },
      { name: t('Urgencias 24 horas'), icon: 'covered' },
    ]
  },
  {
    id: 8,
    title: t('Asisa Dental Familiar'),
    description: t('Seguro dental familiar con amplias coberturas, tratamientos y un precio único hasta cuatro asegurados.'),
    price: [8, 40],
    variant: undefined,
    coverages: [
      { name: t('Múltiples servicios cubiertos por la póliza sin franquicia'), icon: 'covered' },
      { name: t('Pruebas diagnósticas'), icon: 'covered' },
      { name: t('Odontología preventiva y conservadora'), icon: 'covered' },
      { name: t('Endodoncia'), icon: 'covered' },
      { name: t('Odontopediatría'), icon: 'covered' },
      { name: t('Periodoncia'), icon: 'covered' },
      { name: t('Ortodoncia'), icon: 'covered' },
      { name: t('Prótesis e implantes'), icon: 'covered' },
      { name: t('Cirugía'), icon: 'covered' },
      { name: t('Estética dental'), icon: 'covered' },
      { name: t('Urgencias 24 horas'), icon: 'covered' },
    ]
  },
  {
    id: 9,
    title: t('Asisa Vida Tranquilidad'),
    description: t('La tranquilidad de tener el futuro garantizado. Tu seguro de vida a un precio muy competitivo.'),
    price: [30, 0],
    variant: undefined,
    subtitle_price: t('año'),
    coverages: [],
  },
  {
    id: 10,
    title: t('Asisa Vida Proteccion Hipoteca'),
    description: t('Un seguro de vida que garantiza la estabilidad financiera de tu familia frente a impagos de la hipoteca en caso de fallecimiento o incapacidad.'),
    subtitle_price: t('año'),
    price: [30, 0],
    variant: undefined,
    coverages: [],
  },
  {
    id: 11,
    title: t('Asisa Accidentes'),
    description: t('Seguro de fallecimiento por accidente con cobertura internacional. Elige la indemnización que quieras'),
    price: [11, 36],
    variant: undefined,
    subtitle_price: t('año'),
    coverages: [
      { name: t('Indemnización por fallecimiento'), icon: 'covered' },
      { name: t('Cobertura internacional'), icon: 'covered' },
    ]
  },
  {
    id: 12,
    title: t('Asisa Accidentes Plus 1'),
    description: t('Seguro de fallecimiento por accidente con todas las coberturas que puedas necesitar'),
    price: [20, 88],
    variant: undefined,
    subtitle_price: t('año'),
    coverages: [
      { name: t('Indemnización por fallecimiento'), icon: 'covered' },
      { name: t('Indemnización y renta mensual por invalidez permanente y absoluta'), icon: 'covered' },
      { name: t('Indemnización diaria por hospitalización'), icon: 'covered' },
      { name: t('Cirugía estética reparadora'), icon: 'covered' },
      { name: t('Cobertura internacional'), icon: 'covered' },
    ]
  },
  {
    id: 13,
    title: t('Asisa Accidentes Plus 2'),
    description: t('Seguro de fallecimiento por accidente con todas las coberturas e indemnizaciones más altas'),
    price: [32, 59],
    variant: undefined,
    subtitle_price: t('año'),
    coverages: [
      { name: t('Indemnización por fallecimiento'), icon: 'covered' },
      { name: t('Indemnización y renta mensual por invalidez permanente y absoluta'), icon: 'covered' },
      { name: t('Indemnización diaria por hospitalización'), icon: 'covered' },
      { name: t('Cirugía estética reparadora'), icon: 'covered' },
      { name: t('Cobertura internacional'), icon: 'covered' },
    ]
  },
  {
    id: 14,
    title: t('Seguro Asisa Hospitalización'),
    description: t('Asisa Hospitalización es la mejor solución para asegurados y no asegurados de ASISA, cubriendo tus necesidades y las de tu familia si tuvieras que ser hospitalizado.'),
    price: [26, 90],
    subtitle_price: t('año'),
    coverages: [
      { name: t('Indemnización diaria por hospitalización'), icon: 'covered' },
      { name: t('Cobertura internacional'), icon: 'covered' },
    ]
  },
  {
    id: 15,
    title: t('Seguro Ocaso Asistencia Familiar Plena'),
    price: [7, 50],
    description: t('El seguro de decesos que cuida de ti y de los tuyos.'),
    coverages: [
      { name: t('Asistencia en deceso'), icon: 'covered' },
      { name: t('Asistencia en traslado nacional e internacional'), icon: 'covered' },
      { name: t('Asistencia en viaje en España y en el extranjero'), icon: 'covered' },
      { name: t('Asesoramiento legal y abogado de familia'), icon: 'covered' },
      { name: t('Accidentes complementarios hasta 40.000 €'), icon: 'covered' },
      { name: t('Asistencia en vida diaria'), icon: 'covered' },
      { name: t('Protección digital del menor'), icon: 'covered' },
      { name: t('Asistencia a Residentes'), icon: 'covered' },
      { name: t('Asistencia sanitaria por accidente'), icon: 'covered' },
      { name: t('Subsidio diario por accidente'), icon: 'covered' },
      { name: t('Subsidio diario por accidente'), icon: 'covered' },
    ]
  },
  {
    id: 16,
    title: t('Seguro Asisa Mascotas'),
    price: [9, 15],
    description: t('Con el seguro para mascotas de ASISA tu perro o gato tendrá siempre las mejores coberturas en asistencia veterinaria'),
    coverages: [
      { name: t('Asistencia veterinaria'), icon: 'covered' },
      { name: t('Servicio telefónico de orientación veterinaria'), icon: 'covered' },
      { name: t('Servicio de información Mundo Mascotas'), icon: 'covered' },
      { name: t('Responsabilidad civil'), icon: 'covered' },
      { name: t('Capital en caso de fallecimiento por accidente'), icon: 'covered' },
      { name: t('Capital en caso de robo'), icon: 'covered' },
      { name: t('Gastos por sacrificio y eliminación de restos'), icon: 'covered' },
      { name: t('Servicio de urgencias 24 horas'), icon: 'covered' },
      { name: t('Descuentos'), icon: 'covered' },
    ],
  },
  {
    id: 17,
    title: t('Asisa Travel And You'),
    description: t('Seguro flexible, coberturas necesarias para todo tipo de viaje de negocio, ocio y vacacional. Fácil contratación, adaptable a su duración y destino'),
    price: [14, 73],
    subtitle_price: t('persona y viaje'),
    coverages: [
      { name: t('Asistencia médica y sanitaria en todo el mundo (hasta 100.000€ con Asisa Travel And you y 20.000€ con Asisa Travel And You Basic) '), icon: 'covered' },
      { name: t('Repatriación o transporte sanitario de heridos/enfermos y fallecidos'), icon: 'covered' },
      { name: t('Garantías de equipaje'), icon: 'covered' },
      { name: t('Anulación de viaje'), icon: 'covered' },
      { name: t('Fallecimiento e invalidez por accidente'), icon: 'covered' },
      { name: t('Responsabilidad civil'), icon: 'covered' },
      { name: t('Cobertura en caso de Pandemia'), icon: 'covered' },
    ]
  },
  {
    id: 18,
    title: t('Asisa Travel And You Cruise'),
    description: t('Este seguro de viaje es ideal para quienes quieren no dejar nada al azar para su viaje en crucero'),
    price: [22, 6],
    subtitle_price: t('persona y viaje'),
    coverages: [
      { name: t('Asistencia médica y sanitaria (hasta 100.000€)'), icon: 'covered' },
      { name: t('Repatriación o transporte sanitario de heridos/enfermos y fallecidos'), icon: 'covered' },
      { name: t('Garantías de equipaje'), icon: 'covered' },
      { name: t('Anulación de viaje'), icon: 'covered' },
      { name: t('Fallecimiento e invalidez por accidente'), icon: 'covered' },
      { name: t('Responsabilidad civil'), icon: 'covered' },
      { name: t('Cobertura en caso de Pandemia'), icon: 'covered' },
    ]
  },
  {
    id: 19,
    title: t('Asisa Travel All Year'),
    description: t('Para aquellos viajeros que quieren viajar asegurados todo el año a cualquier destino con toda la tranquilidad en todos sus viajes'),
    price: [362, 39],
    subtitle_price: t('persona y año'),
    coverages: [
      { name: t('Asistencia médica y sanitaria (hasta 150.000€)'), icon: 'covered' },
      { name: t('Repatriación o transporte sanitario de heridos/enfermos y fallecidos'), icon: 'covered' },
      { name: t('Garantías de equipaje'), icon: 'covered' },
      { name: t('Anulación de viaje'), icon: 'covered' },
      { name: t('Fallecimiento e invalidez por accidente'), icon: 'covered' },
      { name: t('Responsabilidad civil'), icon: 'covered' },
      { name: t('Cobertura en caso de Pandemia'), icon: 'covered' },
    ]
  },
  {
    id: 20,
    title: t('Asisa Travel Study'),
    description: t('Seguro de viaje para estudiantes. Ideal para cursos, formaciones, Erasmus y estudios realizados en el extranjero en general'),
    price: [56, 76],
    subtitle_price: t('estudiante'),
    coverages: [
      { name: t('Asistencia médica y sanitaria (hasta 100.000€)'), icon: 'covered' },
      { name: t('Repatriación o transporte sanitario de heridos/enfermos y fallecidos'), icon: 'covered' },
      { name: t('Garantías de equipaje'), icon: 'covered' },
      { name: t('Billete de regreso al país de residencia habitual'), icon: 'covered' },
      { name: t('Fallecimiento e invalidez por accidente'), icon: 'covered' },
      { name: t('Responsabilidad civil'), icon: 'covered' },
      { name: t('Cobertura en caso de Pandemia'), icon: 'covered' },
    ]
  }
])
