export const insuranceListIndex = {
  'health': {
    "myself": [1, 2, 3, 4, 5, 6],
    "family": [1, 2, 3, 4, 5, 6],
    "children": [1, 2, 3, 4, 5, 6],
    "other": [1, 2, 3, 4, 5, 6],
  },
  'dental': {
    "myself": [7],
    "family": [8],
    "children": [7, 8],
    "other": [7, 8],
  },
  'life': {
    "myself": [9, 10],
    "family": [9, 10],
    "children": [9, 10],
    "other": [9, 10],
  },
  'accidents': {
    "myself": [11, 12, 13],
    "family": [11, 12, 13],
    "children": [11, 12, 13],
    "other": [11, 12, 13],
  },
  'hospitalization': {
    "myself": [14],
    "family": [14],
    "children": [14],
    "other": [14],
  },
  'passing': {
    "myself": [15],
    "family": [15],
    "children": [15],
    "other": [15],
  },
  'pets': {
    "myself": [16],
    "family": [16],
    "children": [16],
    "other": [16],
  },

  'travel': {
    "myself": [17, 18, 19, 20],
    "family": [17, 18, 19, 20],
    "children": [20],
    "other": [17, 18, 19, 20],
  },
}
export const insuranceList = [
  {
    id: 1,
    title: 'Asisa Completa ++',
    description: 'Cobertura completa al mejor precio y con un copago un poco más alto. El producto estrella de ASISA.',
    price: [18, 5],
    variant: 'Copago alto',
    coverages: [
      { name: 'Consultas en medicina primaria y especializada', icon: 'covered' },
      { name: 'Pruebas diagnósticas', icon: 'covered' },
      { name: 'Tratamientos especiales', icon: 'covered' },
      { name: 'Hospitalización', icon: 'covered' },
      { name: 'Cirugía ambulatoria', icon: 'covered' },
      { name: 'Traslado en ambulancia', icon: 'covered' },
      { name: 'Prótesis e implantes', icon: 'covered' },
      { name: 'Trasplantes', icon: 'covered' },
      { name: 'Indemnización fallecimiento por accidente', icon: 'not-covered' },
    ]
  },
  {
    id: 2,
    title: 'Asisa Ya',
    description: 'Cobertura ambulatoria al mejor precio y con un copago un poco más alto. El producto ambulatorio estrella de ASISA.',
    price: [10, 50],
    variant: 'Copago alto',
    coverages: [
      { name: 'Consultas en medicina primaria y especializada', icon: 'covered', },
      { name: 'Pruebas diagnósticas', icon: 'covered', },
      { name: 'Tratamientos especiales', icon: 'maybe', },
      { name: 'Hospitalización', icon: 'not-covered', },
      { name: 'Cirugía ambulatoria', icon: 'not-covered', },
      { name: 'Traslado en ambulancia', icon: 'covered', },
      { name: 'Prótesis e implantes', icon: 'not-covered', },
      { name: 'Trasplantes', icon: 'not-covered', },
      { name: 'Indemnización fallecimiento por accidente', icon: 'not-covered', },
    ]
  },
  {
    id: 3,
    title: 'Asisa Completa +',
    description: 'Cobertura completa con un precio muy competitivo y un copago bajo.El seguro más vendido de ASISA.',
    price: [26, 80],
    variant: 'Copago bajo',
    coverages: [
      { name: 'Consultas en medicina primaria y especializada', icon: 'covered', },
      { name: 'Pruebas diagnósticas', icon: 'covered', },
      { name: 'Tratamientos especiales', icon: 'covered', },
      { name: 'Hospitalización', icon: 'covered', },
      { name: 'Cirugía ambulatoria', icon: 'covered', },
      { name: 'Traslado en ambulancia', icon: 'covered', },
      { name: 'Prótesis e implantes', icon: 'covered', },
      { name: 'Trasplantes', icon: 'covered', },
      { name: 'Indemnización fallecimiento por accidente', icon: 'not-covered', },
    ]
  },
  {
    id: 4,
    title: 'Asisa Completa',
    description: 'Cobertura completa con un precio muy competitivo y sin copago. El seguro más vendido de ASISA.',
    price: [48, 70],
    variant: 'Sin copago',
    coverages: [
      { name: 'Consultas en medicina primaria y especializada', icon: 'covered', },
      { name: 'Pruebas diagnósticas', icon: 'covered', },
      { name: 'Tratamientos especiales', icon: 'covered', },
      { name: 'Hospitalización', icon: 'covered', },
      { name: 'Cirugía ambulatoria', icon: 'covered', },
      { name: 'Traslado en ambulancia', icon: 'covered', },
      { name: 'Prótesis e implantes', icon: 'covered', },
      { name: 'Trasplantes', icon: 'covered', },
      { name: 'Indemnización fallecimiento por accidente', icon: 'not-covered', },
    ]
  },
  {
    id: 5,
    title: 'Asisa Esencial +',
    description: 'Cobertura ambulatoria (no cubre hospitalización) con un precio muy económico y un copago bajo.',
    price: [21, 0],
    variant: 'Copago bajo',
    coverages: [
      { name: 'Consultas en medicina primaria y especializada', icon: 'covered', },
      { name: 'Pruebas diagnósticas', icon: 'covered', },
      { name: 'Tratamientos especiales', icon: 'maybe', },
      { name: 'Hospitalización', icon: 'not-covered', },
      { name: 'Cirugía ambulatoria', icon: 'not-covered', },
      { name: 'Traslado en ambulancia', icon: 'covered', },
      { name: 'Prótesis e implantes', icon: 'not-covered', },
      { name: 'Trasplantes', icon: 'not-covered', },
      { name: 'Indemnización fallecimiento por accidente', icon: 'not-covered', },
    ]
  },
  {
    id: 6,
    title: 'Asisa Esencial',
    description: 'Cobertura ambulatoria (no cubre hospitalización) con un precio muy económico y sin copago.',
    price: [31, 0],
    variant: 'Sin copago',
    coverages: [
      { name: 'Consultas en medicina primaria y especializada', icon: 'covered', },
      { name: 'Pruebas diagnósticas', icon: 'covered', },
      { name: 'Tratamientos especiales', icon: 'maybe', },
      { name: 'Hospitalización', icon: 'not-covered', },
      { name: 'Cirugía ambulatoria', icon: 'not-covered', },
      { name: 'Traslado en ambulancia', icon: 'covered', },
      { name: 'Prótesis e implantes', icon: 'not-covered', },
      { name: 'Trasplantes', icon: 'not-covered', },
      { name: 'Indemnización fallecimiento por accidente', icon: 'not-covered', },
    ]
  },
  {
    id: 7,
    title: 'Asisa Dental',
    description: 'Seguro dental individual con un gran número de coberturas, tratamientos y una gran red de clínicas a nivel nacional.',
    price: [8, 40],
    variant: undefined,
    coverages: [
      { name: 'Múltiples servicios cubiertos por la póliza sin franquicia', icon: 'covered' },
      { name: 'Pruebas diagnósticas', icon: 'covered' },
      { name: 'Odontología preventiva y conservadora', icon: 'covered' },
      { name: 'Endodoncia', icon: 'covered' },
      { name: 'Odontopediatría', icon: 'covered' },
      { name: 'Periodoncia', icon: 'covered' },
      { name: 'Ortodoncia', icon: 'covered' },
      { name: 'Prótesis e implantes', icon: 'covered' },
      { name: 'Cirugía', icon: 'covered' },
      { name: 'Estética dental', icon: 'covered' },
      { name: 'Urgencias 24 horas', icon: 'covered' },
    ]
  },
  {
    id: 8,
    title: 'Asisa Dental Familiar',
    description: 'Seguro dental familiar con amplias coberturas, tratamientos y un precio único hasta cuatro asegurados.',
    price: [8, 40],
    variant: undefined,
    coverages: [
      { name: 'Múltiples servicios cubiertos por la póliza sin franquicia', icon: 'covered' },
      { name: 'Pruebas diagnósticas', icon: 'covered' },
      { name: 'Odontología preventiva y conservadora', icon: 'covered' },
      { name: 'Endodoncia', icon: 'covered' },
      { name: 'Odontopediatría', icon: 'covered' },
      { name: 'Periodoncia', icon: 'covered' },
      { name: 'Ortodoncia', icon: 'covered' },
      { name: 'Prótesis e implantes', icon: 'covered' },
      { name: 'Cirugía', icon: 'covered' },
      { name: 'Estética dental', icon: 'covered' },
      { name: 'Urgencias 24 horas', icon: 'covered' },
    ]
  },
  {
    id: 9,
    title: 'Asisa Vida Tranquilidad',
    description: 'La tranquilidad de tener el futuro garantizado. Tu seguro de vida a un precio muy competitivo',
    price: [30, 0],
    variant: undefined,
    subtitle_price: 'año',
    coverages: [],
  },
  {
    id: 10,
    title: 'Asisa Vida Proteccion Hipoteca',
    description: 'Un seguro de vida que garantiza la estabilidad financiera de tu familia frente a impagos de la hipoteca en caso de fallecimiento o incapacidad',
    subtitle_price: 'año',
    price: [30, 0],
    variant: undefined,
    coverages: [],
  },
  {
    id: 11,
    title: 'Asisa Accidentes',
    description: 'Seguro de fallecimiento por accidente con cobertura internacional. Elige la indemnización que quieras',
    price: [11, 36],
    variant: undefined,
    subtitle_price: 'año',
    coverages: [
      { name: 'Indemnización por fallecimiento', icon: 'covered' },
      { name: 'Cobertura internacional', icon: 'covered' },
    ]
  },
  {
    id: 12,
    title: 'Asisa Accidentes Plus 1',
    description: 'Seguro de fallecimiento por accidente con todas las coberturas que puedas necesitar',
    price: [20, 88],
    variant: undefined,
    subtitle_price: 'año',
    coverages: [
      { name: 'Indemnización por fallecimiento', icon: 'covered' },
      { name: 'Indemnización y renta mensual por invalidez permanente y absoluta', icon: 'covered' },
      { name: 'Indemnización diaria por hospitalización', icon: 'covered' },
      { name: 'Cirugía estética reparadora', icon: 'covered' },
      { name: 'Cobertura internacional', icon: 'covered' },
    ]
  },
  {
    id: 13,
    title: 'Asisa Accidentes Plus 2',
    description: 'Seguro de fallecimiento por accidente con todas las coberturas e indemnizaciones más altas',
    price: [32, 59],
    variant: undefined,
    subtitle_price: 'año',
    coverages: [
      { name: 'Indemnización por fallecimiento', icon: 'covered' },
      { name: 'Indemnización y renta mensual por invalidez permanente y absoluta', icon: 'covered' },
      { name: 'Indemnización diaria por hospitalización', icon: 'covered' },
      { name: 'Cirugía estética reparadora', icon: 'covered' },
      { name: 'Cobertura internacional', icon: 'covered' },
    ]
  },
  {
    id: 14,
    title: 'Seguro Asisa Hospitalización',
    description: 'Asisa Hospitalización es la mejor solución para asegurados y no asegurados de ASISA, cubriendo tus necesidades y las de tu familia si tuvieras que ser hospitalizado.',
    price: [26, 90],
    subtitle_price: 'año',
    coverages: [
      { name: 'Indemnización diaria por hospitalización', icon: 'covered' },
      { name: 'Cobertura internacional', icon: 'covered' },
    ]
  },
  {
    id: 15,
    title: 'Seguro Ocaso Asistencia Familiar Plena',
    price: [7, 50],
    description: 'El seguro de decesos que cuida de ti y de los tuyos.',
    coverages: [
      { name: 'Asistencia en deceso', icon: 'covered' },
      { name: 'Asistencia en traslado nacional e internacional', icon: 'covered' },
      { name: 'Asistencia en viaje en España y en el extranjero', icon: 'covered' },
      { name: 'Asesoramiento legal y abogado de familia', icon: 'covered' },
      { name: 'Accidentes complementarios hasta 40.000 €', icon: 'covered' },
      { name: 'Asistencia en vida diaria', icon: 'covered' },
      { name: 'Protección digital del menor', icon: 'covered' },
      { name: 'Asistencia a Residentes', icon: 'covered' },
      { name: 'Asistencia sanitaria por accidente', icon: 'covered' },
      { name: 'Subsidio diario por accidente', icon: 'covered' },
      { name: 'Subsidio diario por accidente', icon: 'covered' },
    ]
  },
  {
    id: 16,
    title: 'Seguro Asisa Mascotas',
    price: [9, 15],
    description: 'Con el seguro para mascotas de ASISA tu perro o gato tendrá siempre las mejores coberturas en asistencia veterinaria',
    coverages: [
      { name: 'Asistencia veterinaria', icon: 'covered' },
      { name: 'Servicio telefónico de orientación veterinaria', icon: 'covered' },
      { name: 'Servicio de información Mundo Mascotas', icon: 'covered' },
      { name: 'Responsabilidad civil', icon: 'covered' },
      { name: 'Capital en caso de fallecimiento por accidente', icon: 'covered' },
      { name: 'Capital en caso de robo', icon: 'covered' },
      { name: 'Gastos por sacrificio y eliminación de restos', icon: 'covered' },
      { name: 'Servicio de urgencias 24 horas', icon: 'covered' },
      { name: 'Descuentos', icon: 'covered' },
    ],
  },
  {
    id: 17,
    title: 'Asisa Travel And You',
    description: 'Seguro flexible, coberturas necesarias para todo tipo de viaje de negocio, ocio y vacacional. Fácil contratación, adaptable a su duración y destino',
    price: [14, 73],
    subtitle_price: 'persona y viaje',
    coverages: [
      { name: 'Asistencia médica y sanitaria en todo el mundo (hasta 100.000€ con Asisa Travel And you y 20.000€ con Asisa Travel And You Basic) ', icon: 'covered' },
      { name: 'Repatriación o transporte sanitario de heridos/enfermos y fallecidos', icon: 'covered' },
      { name: 'Garantías de equipaje', icon: 'covered' },
      { name: 'Anulación de viaje', icon: 'covered' },
      { name: 'Fallecimiento e invalidez por accidente', icon: 'covered' },
      { name: 'Responsabilidad civil', icon: 'covered' },
      { name: 'Cobertura en caso de Pandemia', icon: 'covered' },
    ]
  },
  {
    id: 18,
    title: 'Asisa Travel And You Cruise',
    description: 'Este seguro de viaje es ideal para quienes quieren no dejar nada al azar para su viaje en crucero',
    price: [22, 6],
    subtitle_price: 'persona y viaje',
    coverages: [
      { name: 'Asistencia médica y sanitaria (hasta 100.000€)', icon: 'covered' },
      { name: 'Repatriación o transporte sanitario de heridos/enfermos y fallecidos', icon: 'covered' },
      { name: 'Garantías de equipaje', icon: 'covered' },
      { name: 'Anulación de viaje', icon: 'covered' },
      { name: 'Fallecimiento e invalidez por accidente', icon: 'covered' },
      { name: 'Responsabilidad civil', icon: 'covered' },
      { name: 'Cobertura en caso de Pandemia', icon: 'covered' },
    ]
  },
  {
    id: 19,
    title: 'Asisa Travel All Year',
    description: 'Para aquellos viajeros que quieren viajar asegurados todo el año a cualquier destino con toda la tranquilidad en todos sus viajes',
    price: [362, 39],
    subtitle_price: 'persona y año',
    coverages: [
      { name: 'Asistencia médica y sanitaria (hasta 150.000€)', icon: 'covered' },
      { name: 'Repatriación o transporte sanitario de heridos/enfermos y fallecidos', icon: 'covered' },
      { name: 'Garantías de equipaje', icon: 'covered' },
      { name: 'Anulación de viaje', icon: 'covered' },
      { name: 'Fallecimiento e invalidez por accidente', icon: 'covered' },
      { name: 'Responsabilidad civil', icon: 'covered' },
      { name: 'Cobertura en caso de Pandemia', icon: 'covered' },
    ]
  },
  {
    id: 20,
    title: 'Asisa Travel Study',
    description: 'Seguro de viaje para estudiantes. Ideal para cursos, formaciones, Erasmus y estudios realizados en el extranjero en general',
    price: [56, 76],
    subtitle_price: 'estudiante',
    coverages: [
      { name: 'Asistencia médica y sanitaria (hasta 100.000€)', icon: 'covered' },
      { name: 'Repatriación o transporte sanitario de heridos/enfermos y fallecidos', icon: 'covered' },
      { name: 'Garantías de equipaje', icon: 'covered' },
      { name: 'Billete de regreso al país de residencia habitual', icon: 'covered' },
      { name: 'Fallecimiento e invalidez por accidente', icon: 'covered' },
      { name: 'Responsabilidad civil', icon: 'covered' },
      { name: 'Cobertura en caso de Pandemia', icon: 'covered' },
    ]
  }
]